# Generated by Django 4.1.7 on 2023-09-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemid', models.IntegerField()),
                ('stud_name', models.CharField(max_length=250)),
                ('parent_name', models.CharField(max_length=250)),
                ('parent_contact', models.IntegerField()),
                ('stud_address', models.TextField()),
                ('stud_contact', models.IntegerField()),
                ('qualification', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=250)),
                ('course1', models.CharField(max_length=250)),
                ('course2', models.CharField(max_length=250)),
                ('course3', models.CharField(max_length=250)),
                ('course_duration', models.DateField()),
                ('scheme', models.CharField(max_length=250)),
                ('fee', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('exam_date', models.DateField()),
                ('certificate_status', models.CharField(max_length=250)),
            ],
        ),
    ]
