# Generated by Django 4.1.7 on 2023-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemapp', '0002_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='course_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='exam_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='joining_date',
            field=models.DateField(auto_now=True),
        ),
    ]
