# Generated by Django 4.1.7 on 2023-09-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemapp', '0003_alter_admission_course_duration_alter_admission_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='exam_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
